#!/bin/sh
set -x

if [ -n "$1" ]; then
    # cria interface TAP
    ip tuntap add $1 mode tap user $(whoami)

    # sobe interface
    ip link set $1 up

    # adiciona IP no host (ESSENCIAL)
    ip addr add 192.168.1.1/24 dev $1 2>/dev/null

    # habilita forwarding (opcional)
    sysctl -w net.ipv4.ip_forward=1

    exit 0
else
    echo "Error: no interface specified"
    exit 1
fi