#!/bin/sh

case "$1" in
    start)
        echo "Starting System Info API..."
        /usr/bin/python3 /root/systeminfo.py &
        ;;
    stop)
        killall python3
        ;;
    *)
        exit 1
        ;;
esac

exit 0